/**
 * @section License
 *
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <http://unlicense.org/>
 *
 * This file is part of the Simba project.
 */

/**
 * This file was generated by settings.py 1.0 2016-08-10 17:53 CEST.
 */

#ifndef __SETTINGS_H__
#define __SETTINGS_H__

#include "simba.h"

#define SETTING_INT8_ADDR 0
#define SETTING_INT16_ADDR 1
#define SETTING_INT32_ADDR 4
#define SETTING_STRING_ADDR 8

#define SETTING_INT8_SIZE 1
#define SETTING_INT16_SIZE 2
#define SETTING_INT32_SIZE 4
#define SETTING_STRING_SIZE 4

#define SETTING_INT8_TYPE setting_type_int8_t_t
#define SETTING_INT16_TYPE setting_type_int16_t_t
#define SETTING_INT32_TYPE setting_type_int32_t_t
#define SETTING_STRING_TYPE setting_type_string_t_t

#define SETTING_INT8_VALUE -4
#define SETTING_INT16_VALUE -3
#define SETTING_INT32_VALUE -2
#define SETTING_STRING_VALUE y

#endif
