/**
 * @section License
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2014-2016, Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * This file is part of the Simba project.
 */

/**
 * This file was generated by settings.py 1.0 2017-03-04 18:36 CET.
 */

#ifndef __SETTINGS_H__
#define __SETTINGS_H__

#include "simba.h"

#define SETTING_INT8_ADDR 0
#define SETTING_INT16_ADDR 8
#define SETTING_INT32_ADDR 16
#define SETTING_STRING_ADDR 24

#define SETTING_INT8_SIZE 1
#define SETTING_INT16_SIZE 2
#define SETTING_INT32_SIZE 4
#define SETTING_STRING_SIZE 4

#define SETTING_INT8_TYPE setting_type_int8_t_t
#define SETTING_INT16_TYPE setting_type_int16_t_t
#define SETTING_INT32_TYPE setting_type_int32_t_t
#define SETTING_STRING_TYPE setting_type_string_t_t

#define SETTING_INT8_VALUE -4
#define SETTING_INT16_VALUE -3
#define SETTING_INT32_VALUE -2
#define SETTING_STRING_VALUE y

#endif
