#
# @file SConstruct
# @version 1.0
#
# @section License
# Copyright (C) 2014-2015, Erik Moqvist
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# This file is part of the Simba project.
#

import os

SRC = ["main.c"]

env = DefaultEnvironment()

env.Append(BOARD="linux")
env.Append(NAME="setting_suite")
env.Append(SRC=[os.path.join(os.getcwd(), src) for src in SRC])

env.Append(SETTINGS_INI="#/settings.ini")

SIMBA_ROOT = os.path.abspath(os.environ.get("SIMBA_ROOT", "../../.."))
env.Append(SIMBA_ROOT=SIMBA_ROOT)
SConscript(os.path.join(SIMBA_ROOT, "make", "app.sconscript"))
