#!/usr/bin/env expect

set timeout 10

spawn kermit
expect "C-Kermit>"
send "hangup\r"
expect "C-Kermit>"
send "connect\r"
expect {
    -re "harness report: total\\(\\d+\\), passed\\(\\d+\\), failed\\(\[1-9\]+\\)" {
        close
        sleep 2
        exit 1
    }
    -re "harness report: total\\(\\d+\\), passed\\(\\d+\\), failed\\(0\\)" {
        close
        sleep 2
        exit 0
    }
    timeout {
        close
        sleep 2
        exit 1
    }
}
