/**
 * @file settings.h
 * @version 5.0.0
 *
 * @section License
 * Copyright (C) 2014-2016, Erik Moqvist
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * This file is part of the Simba project.
 */

/**
 * This file was generated by setting.py 1.0 2016-08-08 14:55 CEST.
 */

#ifndef __SETTINGS_H__
#define __SETTINGS_H__

#include "simba.h"

#define SETTING_INT8_ADDR 0
#define SETTING_INT16_ADDR 1
#define SETTING_INT32_ADDR 4
#define SETTING_STRING_ADDR 8

#define SETTING_INT8_SIZE 1
#define SETTING_INT16_SIZE 2
#define SETTING_INT32_SIZE 4
#define SETTING_STRING_SIZE 4

#define SETTING_INT8_TYPE setting_type_int8_t_t
#define SETTING_INT16_TYPE setting_type_int16_t_t
#define SETTING_INT32_TYPE setting_type_int32_t_t
#define SETTING_STRING_TYPE setting_type_string_t_t

#define SETTING_INT8_VALUE -4
#define SETTING_INT16_VALUE -3
#define SETTING_INT32_VALUE -2
#define SETTING_STRING_VALUE y

#endif
