/**
 * @file settings.c
 * @version 5.0.0
 *
 * @section License
 * Copyright (C) 2014-2016, Erik Moqvist
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * This file is part of the Simba project.
 */

/**
 * This file was generated by setting.py 1.0 2016-08-08 14:50 CEST.
 */

#include "simba.h"

const FAR struct setting_t settings[]
__attribute__ ((weak)) = {
    { NULL, 0, 0, 0 }
};

#if defined(ARCH_AVR)

uint8_t setting_area[CONFIG_SETTING_AREA_SIZE]
__attribute__ ((section (".eeprom"), weak)) = {
    0xff,
};

const FAR uint8_t setting_default_area[]
__attribute__ ((weak)) = {
    0xff,
};

#elif defined(ARCH_ARM)

uint8_t setting_area[2][CONFIG_SETTING_AREA_SIZE]
__attribute__ ((section (".setting"), weak)) = {
    {
        0xff,
    },
    {
        0xff,
    }
};

uint8_t setting_default_area[CONFIG_SETTING_AREA_SIZE]
__attribute__ ((section (".setting"), weak)) = {
    0xff,
};

#else

const uint8_t setting_default_area[CONFIG_SETTING_AREA_SIZE]
__attribute__ ((weak)) = {
    0xff,
};

#endif
